=== madytw/RMI/Server/src/main/resources/students.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.com/students"
        xmlns:tns="http://www.example.com/students"
        elementFormDefault="qualified">

    <element name="table" type="tns:table-type" abstract="true"></element>
    <element name="student" type="tns:student" substitutionGroup="tns:table"></element>
    <element name="result" type="tns:result" substitutionGroup="tns:table"></element>

    <element name="session">
        <complexType>
            <sequence>
                <element ref="tns:table" minOccurs="1" maxOccurs="unbounded"/>
                <!--<element name="student"-->
                            <!--type="tns:student"  minOccurs="1" maxOccurs="unbounded"/>-->
                <!--<element name="result"-->
                         <!--type="tns:result"  minOccurs="1" maxOccurs="unbounded"/>-->
            </sequence>
        </complexType>
    </element>

    <complexType name="student">
        <complexContent>
            <extension base="tns:table-type">
                <sequence>
                    <element name="surname" type="string"/>
                    <element name="group" type="integer"/>
                </sequence>
                <attribute name="id" use="required" type="integer"/>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="result">
        <complexContent>
            <extension base="tns:table-type">
                <sequence>
                    <element name="subject" type="string"/>
                    <element name="mark" type="integer"/>
                </sequence>
                <attribute name="student_id" use="required" type="integer"/>
            </extension>
        </complexContent>

    </complexType>

    <complexType name="table-type"></complexType>
</schema>

=== madytw/RMI/Server/src/main/resources/students.xml
<?xml version="1.0" encoding="UTF-8"?><session xmlns="http://www.example.com/students" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.com/students students.xsd">
    <student id="1">
        <surname>Гриневский</surname>
        <group>1</group>
    </student>
    <student id="2">
        <surname>Авижень</surname>
        <group>1</group>
    </student>
    <student id="3">
        <surname>Козлов</surname>
        <group>3</group>
    </student>
    <student id="4">
        <surname>Пупкин</surname>
        <group>3</group>
    </student>
    <student id="5">
        <surname>Петрова</surname>
        <group>2</group>
    </student>
    <student id="6">
        <surname>Сидорова</surname>
        <group>2</group>
    </student>
    <result student_id="1">
        <subject>МА</subject>
        <mark>8</mark>
    </result>
    <result student_id="1">
        <subject>ГА</subject>
        <mark>8</mark>
    </result>
    <result student_id="1">
        <subject>ТВиМС</subject>
        <mark>6</mark>
    </result>
    <result student_id="2">
        <subject>МА</subject>
        <mark>6</mark>
    </result>
    <result student_id="2">
        <subject>ГА</subject>
        <mark>7</mark>
    </result>
    <result student_id="2">
        <subject>ТВиМС</subject>
        <mark>9</mark>
    </result>
    <result student_id="3">
        <subject>МА</subject>
        <mark>3</mark>
    </result>
    <result student_id="3">
        <subject>ГА</subject>
        <mark>4</mark>
    </result>
    <result student_id="3">
        <subject>ТВиМС</subject>
        <mark>4</mark>
    </result>
    <result student_id="4">
        <subject>МА</subject>
        <mark>9</mark>
    </result>
    <result student_id="4">
        <subject>ГА</subject>
        <mark>9</mark>
    </result>
    <result student_id="4">
        <subject>ТВиМС</subject>
        <mark>9</mark>
    </result>
    <result student_id="5">
        <subject>МА</subject>
        <mark>10</mark>
    </result>
    <result student_id="5">
        <subject>ГА</subject>
        <mark>10</mark>
    </result>
    <result student_id="5">
        <subject>ТВиМС</subject>
        <mark>10</mark>
    </result>
    <result student_id="6">
        <subject>МА</subject>
        <mark>8</mark>
    </result>
    <result student_id="6">
        <subject>ГА</subject>
        <mark>1</mark>
    </result>
    <result student_id="6">
        <subject>ТВиМС</subject>
        <mark>7</mark>
    </result>
</session>
